apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons-by-cluster
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/segoja7/platform_as_data
        revision: master
        directories:
          - path: xargoapps/gitops-bridge/one_to_one/clusters/*

  template:
    metadata:
      name: 'addons-{{.path.basename}}'
      namespace: 'argocd'
    spec:
      project: default
      source:
        repoURL: https://github.com/segoja7/platform_as_data
        targetRevision: master
        path: '{{.path.path}}'
        directory:
          recurse: true
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: 'argocd'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true