# xargoapps/gitops-bridge/cluster-centric-pattern/applicationset.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons-by-cluster
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: environment
              operator: NotIn
              values: [hub]
  template:
    metadata:
      name: 'addons-{{name}}'
      namespace: 'argocd'
    spec:
      project: default
      source:
        repoURL: '{{metadata.annotations.addons_repo_url}}'
        targetRevision: '{{metadata.annotations.addons_repo_revision}}'
        path: 'xargoapps/gitops-bridge/one_to_one/clusters/{{name}}'
        directory:
          recurse: true
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: 'argocd'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
