# xargoapps/gitops-bridge/cluster-centric-pattern/applicationset.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons-by-cluster
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: environment
              operator: NotIn
              values: [hub]
  template:
    metadata:
      # Nombre de la App: addons-spoke-1, addons-spoke-2
      name: 'addons-{{name}}'
      namespace: 'argocd'
    spec:
      project: default
      source:
        repoURL: '{{metadata.annotations.addons_repo_url}}'
        targetRevision: '{{metadata.annotations.addons_repo_revision}}'
        # Ruta dinámica a la carpeta del cluster
        path: 'xargoapps/gitops-bridge/cluster-centric-pattern/clusters/{{name}}'
        # Habilitar la búsqueda recursiva en subdirectorios
        directory:
          recurse: true
      destination:
        name: '{{name}}'
        namespace: 'default' # Namespace por defecto, puede ser sobreescrito por los manifiestos
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
