apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../catalog/nginx # Ruta relativa a la base en catalog


# commonLabels:
#   app.kubernetes.io/managed-by: argocd-master-controller
